# CJK Chinese (GB) tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr

module CharConv::Tables::CJKGB

  # --- GBK: lead 0x81-0xFE, trail 0x40-0xFE ---
  GBK_LEAD_MIN = 0x81
  GBK_LEAD_MAX = 0xFE
  GBK_TRAIL_MIN = 0x40
  GBK_TRAIL_MAX = 0xFE
  GBK_TRAIL_COUNT = 191

  private RAW_GBK_DECODE = {{ read_file("#{__DIR__}/data/gbk_decode.bin") }}
  GBK_DECODE = Slice.new(RAW_GBK_DECODE.to_unsafe.as(Pointer(UInt16)), 24066)

  private RAW_GBK_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/gbk_encode_summary.bin") }}
  GBK_ENCODE_SUMMARY = Slice.new(RAW_GBK_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_GBK_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/gbk_encode_pages.bin") }}
  GBK_ENCODE_PAGES = begin
    ptr = RAW_GBK_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(129) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- EUCCN: lead 0xA1-0xF7, trail 0xA1-0xFE ---
  EUCCN_LEAD_MIN = 0xA1
  EUCCN_LEAD_MAX = 0xF7
  EUCCN_TRAIL_MIN = 0xA1
  EUCCN_TRAIL_MAX = 0xFE
  EUCCN_TRAIL_COUNT = 94

  private RAW_EUCCN_DECODE = {{ read_file("#{__DIR__}/data/euccn_decode.bin") }}
  EUCCN_DECODE = Slice.new(RAW_EUCCN_DECODE.to_unsafe.as(Pointer(UInt16)), 8178)

  private RAW_EUCCN_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/euccn_encode_summary.bin") }}
  EUCCN_ENCODE_SUMMARY = Slice.new(RAW_EUCCN_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_EUCCN_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/euccn_encode_pages.bin") }}
  EUCCN_ENCODE_PAGES = begin
    ptr = RAW_EUCCN_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(97) { |i| Slice.new(ptr + i * 256, 256) }
  end
end
