# CJK Korean tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr

module CharConv::Tables::CJKKSC

  # --- EUCKR: lead 0xA1-0xFE, trail 0xA1-0xFE ---
  EUCKR_LEAD_MIN = 0xA1
  EUCKR_LEAD_MAX = 0xFE
  EUCKR_TRAIL_MIN = 0xA1
  EUCKR_TRAIL_MAX = 0xFE
  EUCKR_TRAIL_COUNT = 94

  private RAW_EUCKR_DECODE = {{ read_file("#{__DIR__}/data/euckr_decode.bin") }}
  EUCKR_DECODE = Slice.new(RAW_EUCKR_DECODE.to_unsafe.as(Pointer(UInt16)), 8836)

  private RAW_EUCKR_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/euckr_encode_summary.bin") }}
  EUCKR_ENCODE_SUMMARY = Slice.new(RAW_EUCKR_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_EUCKR_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/euckr_encode_pages.bin") }}
  EUCKR_ENCODE_PAGES = begin
    ptr = RAW_EUCKR_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(145) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- CP949: lead 0x81-0xFE, trail 0x41-0xFE ---
  CP949_LEAD_MIN = 0x81
  CP949_LEAD_MAX = 0xFE
  CP949_TRAIL_MIN = 0x41
  CP949_TRAIL_MAX = 0xFE
  CP949_TRAIL_COUNT = 190

  private RAW_CP949_DECODE = {{ read_file("#{__DIR__}/data/cp949_decode.bin") }}
  CP949_DECODE = Slice.new(RAW_CP949_DECODE.to_unsafe.as(Pointer(UInt16)), 23940)

  private RAW_CP949_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/cp949_encode_summary.bin") }}
  CP949_ENCODE_SUMMARY = Slice.new(RAW_CP949_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_CP949_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/cp949_encode_pages.bin") }}
  CP949_ENCODE_PAGES = begin
    ptr = RAW_CP949_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(149) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- JOHAB: lead 0x84-0xF9, trail 0x31-0xFE ---
  JOHAB_LEAD_MIN = 0x84
  JOHAB_LEAD_MAX = 0xF9
  JOHAB_TRAIL_MIN = 0x31
  JOHAB_TRAIL_MAX = 0xFE
  JOHAB_TRAIL_COUNT = 206

  private RAW_JOHAB_DECODE = {{ read_file("#{__DIR__}/data/johab_decode.bin") }}
  JOHAB_DECODE = Slice.new(RAW_JOHAB_DECODE.to_unsafe.as(Pointer(UInt16)), 24308)

  private RAW_JOHAB_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/johab_encode_summary.bin") }}
  JOHAB_ENCODE_SUMMARY = Slice.new(RAW_JOHAB_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_JOHAB_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/johab_encode_pages.bin") }}
  JOHAB_ENCODE_PAGES = begin
    ptr = RAW_JOHAB_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(145) { |i| Slice.new(ptr + i * 256, 256) }
  end
end
