# CJK Japanese tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr

module CharConv::Tables::CJKJis

  # --- EUCJP: lead 0xA1-0xFE, trail 0xA1-0xFE ---
  EUCJP_LEAD_MIN = 0xA1
  EUCJP_LEAD_MAX = 0xFE
  EUCJP_TRAIL_MIN = 0xA1
  EUCJP_TRAIL_MAX = 0xFE
  EUCJP_TRAIL_COUNT = 94

  private RAW_EUCJP_DECODE = {{ read_file("#{__DIR__}/data/eucjp_decode.bin") }}
  EUCJP_DECODE = Slice.new(RAW_EUCJP_DECODE.to_unsafe.as(Pointer(UInt16)), 8836)

  private RAW_EUCJP_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/eucjp_encode_summary.bin") }}
  EUCJP_ENCODE_SUMMARY = Slice.new(RAW_EUCJP_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_EUCJP_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/eucjp_encode_pages.bin") }}
  EUCJP_ENCODE_PAGES = begin
    ptr = RAW_EUCJP_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(93) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- SHIFTJIS: lead 0x81-0xEF, trail 0x40-0xFC ---
  SHIFTJIS_LEAD_MIN = 0x81
  SHIFTJIS_LEAD_MAX = 0xEF
  SHIFTJIS_TRAIL_MIN = 0x40
  SHIFTJIS_TRAIL_MAX = 0xFC
  SHIFTJIS_TRAIL_COUNT = 189

  private RAW_SHIFTJIS_DECODE = {{ read_file("#{__DIR__}/data/shiftjis_decode.bin") }}
  SHIFTJIS_DECODE = Slice.new(RAW_SHIFTJIS_DECODE.to_unsafe.as(Pointer(UInt16)), 20979)

  private RAW_SHIFTJIS_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/shiftjis_encode_summary.bin") }}
  SHIFTJIS_ENCODE_SUMMARY = Slice.new(RAW_SHIFTJIS_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_SHIFTJIS_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/shiftjis_encode_pages.bin") }}
  SHIFTJIS_ENCODE_PAGES = begin
    ptr = RAW_SHIFTJIS_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(93) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- CP932: lead 0x81-0xFC, trail 0x40-0xFC ---
  CP932_LEAD_MIN = 0x81
  CP932_LEAD_MAX = 0xFC
  CP932_TRAIL_MIN = 0x40
  CP932_TRAIL_MAX = 0xFC
  CP932_TRAIL_COUNT = 189

  private RAW_CP932_DECODE = {{ read_file("#{__DIR__}/data/cp932_decode.bin") }}
  CP932_DECODE = Slice.new(RAW_CP932_DECODE.to_unsafe.as(Pointer(UInt16)), 23436)

  private RAW_CP932_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/cp932_encode_summary.bin") }}
  CP932_ENCODE_SUMMARY = Slice.new(RAW_CP932_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_CP932_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/cp932_encode_pages.bin") }}
  CP932_ENCODE_PAGES = begin
    ptr = RAW_CP932_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(106) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # SHIFTJIS single-byte decode/encode
  private RAW_SHIFTJIS_SINGLE_DECODE = {{ read_file("#{__DIR__}/data/shiftjis_single_decode.bin") }}
  SHIFTJIS_SINGLE_DECODE = Slice.new(RAW_SHIFTJIS_SINGLE_DECODE.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_SHIFTJIS_SINGLE_ENCODE_PAIRS = {{ read_file("#{__DIR__}/data/shiftjis_single_encode_pairs.bin") }}
  SHIFTJIS_SINGLE_ENCODE_PAIRS = begin
    data = RAW_SHIFTJIS_SINGLE_ENCODE_PAIRS.to_slice
    count = data.size // 3
    Array({UInt16, UInt8}).new(count) do |i|
      off = i * 3
      cp = (data[off].to_u16 | (data[off + 1].to_u16 << 8))
      byte = data[off + 2]
      {cp, byte}
    end
  end

  # CP932 single-byte decode/encode
  private RAW_CP932_SINGLE_DECODE = {{ read_file("#{__DIR__}/data/cp932_single_decode.bin") }}
  CP932_SINGLE_DECODE = Slice.new(RAW_CP932_SINGLE_DECODE.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_CP932_SINGLE_ENCODE_PAIRS = {{ read_file("#{__DIR__}/data/cp932_single_encode_pairs.bin") }}
  CP932_SINGLE_ENCODE_PAIRS = begin
    data = RAW_CP932_SINGLE_ENCODE_PAIRS.to_slice
    count = data.size // 3
    Array({UInt16, UInt8}).new(count) do |i|
      off = i * 3
      cp = (data[off].to_u16 | (data[off + 1].to_u16 << 8))
      byte = data[off + 2]
      {cp, byte}
    end
  end
end
