# CJK BIG5 family tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr

module CharConv::Tables::CJKBig5

  # --- BIG5: lead 0x81-0xFE, trail 0x40-0xFE ---
  BIG5_LEAD_MIN = 0x81
  BIG5_LEAD_MAX = 0xFE
  BIG5_TRAIL_MIN = 0x40
  BIG5_TRAIL_MAX = 0xFE
  BIG5_TRAIL_COUNT = 191

  private RAW_BIG5_DECODE = {{ read_file("#{__DIR__}/data/big5_decode.bin") }}
  BIG5_DECODE = Slice.new(RAW_BIG5_DECODE.to_unsafe.as(Pointer(UInt16)), 24066)

  private RAW_BIG5_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/big5_encode_summary.bin") }}
  BIG5_ENCODE_SUMMARY = Slice.new(RAW_BIG5_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_BIG5_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/big5_encode_pages.bin") }}
  BIG5_ENCODE_PAGES = begin
    ptr = RAW_BIG5_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(129) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- CP950: lead 0x81-0xFE, trail 0x40-0xFE ---
  CP950_LEAD_MIN = 0x81
  CP950_LEAD_MAX = 0xFE
  CP950_TRAIL_MIN = 0x40
  CP950_TRAIL_MAX = 0xFE
  CP950_TRAIL_COUNT = 191

  private RAW_CP950_DECODE = {{ read_file("#{__DIR__}/data/cp950_decode.bin") }}
  CP950_DECODE = Slice.new(RAW_CP950_DECODE.to_unsafe.as(Pointer(UInt16)), 24066)

  private RAW_CP950_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/cp950_encode_summary.bin") }}
  CP950_ENCODE_SUMMARY = Slice.new(RAW_CP950_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_CP950_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/cp950_encode_pages.bin") }}
  CP950_ENCODE_PAGES = begin
    ptr = RAW_CP950_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(97) { |i| Slice.new(ptr + i * 256, 256) }
  end

  # --- BIG5HKSCS: lead 0x81-0xFE, trail 0x40-0xFE ---
  BIG5HKSCS_LEAD_MIN = 0x81
  BIG5HKSCS_LEAD_MAX = 0xFE
  BIG5HKSCS_TRAIL_MIN = 0x40
  BIG5HKSCS_TRAIL_MAX = 0xFE
  BIG5HKSCS_TRAIL_COUNT = 191

  private RAW_BIG5HKSCS_DECODE = {{ read_file("#{__DIR__}/data/big5hkscs_decode.bin") }}
  BIG5HKSCS_DECODE = Slice.new(RAW_BIG5HKSCS_DECODE.to_unsafe.as(Pointer(UInt16)), 24066)

  private RAW_BIG5HKSCS_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/big5hkscs_encode_summary.bin") }}
  BIG5HKSCS_ENCODE_SUMMARY = Slice.new(RAW_BIG5HKSCS_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_BIG5HKSCS_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/big5hkscs_encode_pages.bin") }}
  BIG5HKSCS_ENCODE_PAGES = begin
    ptr = RAW_BIG5HKSCS_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(225) { |i| Slice.new(ptr + i * 256, 256) }
  end
end
