# CJK EUC-TW tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr

module CharConv::Tables::CJKEUCTW

  # EUCTW: lead 0xA1-0xFE, trail 0xA1-0xFE
  EUCTW_LEAD_MIN = 0xA1
  EUCTW_LEAD_MAX = 0xFE
  EUCTW_TRAIL_MIN = 0xA1
  EUCTW_TRAIL_MAX = 0xFE
  EUCTW_TRAIL_COUNT = 94

  private RAW_EUCTW_DECODE = {{ read_file("#{__DIR__}/data/euctw_decode.bin") }}
  EUCTW_DECODE = Slice.new(RAW_EUCTW_DECODE.to_unsafe.as(Pointer(UInt16)), 8836)

  private RAW_EUCTW_ENCODE_SUMMARY = {{ read_file("#{__DIR__}/data/euctw_encode_summary.bin") }}
  EUCTW_ENCODE_SUMMARY = Slice.new(RAW_EUCTW_ENCODE_SUMMARY.to_unsafe.as(Pointer(UInt16)), 256)

  private RAW_EUCTW_ENCODE_PAGES = {{ read_file("#{__DIR__}/data/euctw_encode_pages.bin") }}
  EUCTW_ENCODE_PAGES = begin
    ptr = RAW_EUCTW_ENCODE_PAGES.to_unsafe.as(Pointer(UInt16))
    Array(Slice(UInt16)).new(98) { |i| Slice.new(ptr + i * 256, 256) }
  end
end
