# Single-byte codec tables — loaded from precomputed binary data.
# Binary files generated by tools/dump_binary_tables.cr
#
# Each DECODE table is 256 entries mapping byte 0x00-0xFF to Unicode codepoints.
# 0xFFFF = undefined (ILSEQ).
# Each ENCODE_PAIRS array lists {codepoint, byte} from system iconv's encode direction.

module CharConv::Tables::SingleByte
  private def self.load_decode(raw : String) : StaticArray(UInt16, 256)
    ptr = raw.to_unsafe.as(Pointer(UInt16))
    StaticArray(UInt16, 256).new { |i| ptr[i] }
  end

  private def self.load_pairs(raw : String) : Array({UInt16, UInt8})
    data = raw.to_slice
    count = data.size // 3
    Array({UInt16, UInt8}).new(count) do |i|
      off = i * 3
      cp = (data[off].to_u16 | (data[off + 1].to_u16 << 8))
      byte = data[off + 2]
      {cp, byte}
    end
  end

  {% for enc in %w[
    ISO_8859_2 ISO_8859_3 ISO_8859_4 ISO_8859_5 ISO_8859_6 ISO_8859_7
    ISO_8859_8 ISO_8859_9 ISO_8859_10 ISO_8859_11 ISO_8859_13 ISO_8859_14
    ISO_8859_15 ISO_8859_16
    CP1250 CP1251 CP1252 CP1253 CP1254 CP1255 CP1256 CP1257 CP1258
    KOI8_R KOI8_U KOI8_RU
    MAC_ROMAN MAC_CENTRAL_EUROPE MAC_ICELAND MAC_CROATIAN MAC_ROMANIA
    MAC_CYRILLIC MAC_UKRAINE MAC_GREEK MAC_TURKISH MAC_HEBREW MAC_ARABIC MAC_THAI
    CP437 CP737 CP775 CP850 CP852 CP855 CP857 CP858 CP860 CP861 CP862 CP863
    CP864 CP865 CP866 CP869
    CP874 TIS_620 VISCII ARMSCII_8 GEORGIAN_ACADEMY GEORGIAN_PS HP_ROMAN8
    NEXTSTEP PT154 KOI8_T
    CP037 CP273 CP277 CP278 CP280 CP284 CP285 CP297
    CP423 CP424 CP500 CP905 CP1026
    CP856 CP922 CP853 CP1046 CP1124 CP1125 CP1129 CP1131
    CP1133 CP1161 CP1162 CP1163 ATARIST KZ_1048 MULELAO_1 RISCOS_LATIN1
    TCVN
  ] %}
    private RAW_{{ enc.id }}_DECODE = {{ read_file("#{__DIR__}/data/sb_#{enc.downcase.id}_decode.bin") }}
    {{ enc.id }}_DECODE = load_decode(RAW_{{ enc.id }}_DECODE)
    private RAW_{{ enc.id }}_ENCODE_PAIRS = {{ read_file("#{__DIR__}/data/sb_#{enc.downcase.id}_encode_pairs.bin") }}
    {{ enc.id }}_ENCODE_PAIRS = load_pairs(RAW_{{ enc.id }}_ENCODE_PAIRS)
  {% end %}
end
